version: "2"
volumes:
    resin-data:
services:
  mosquitto:
    privileged: true
    restart: always
    build:
      context: ./mosquitto
    volumes:
      - resin-data:/data
    ports:
      - 1883:1883
  thermometer:
    privileged: true
    restart: always
    build:
      context: ./thermometer
  hass:
    privileged: true
    restart: always
    build: ./resin-homeassistant
    expose:
      - 80
    ports:
      - 80:8123
    depends_on:
      - mosquitto
    volumes:
      - resin-data:/data
